areaDirs = {
  ['maritime']       = {area = [[The Maritime Museum]], dstRoom = [[The Entrance]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;w]], needKeys = false},
  ['dragoncaves']    = {area = [[The Dragon Caves]], dstRoom = [[A Path Through the Valley]], dirs = [[#12 w;#2 s;w;s;e;#2 s;#4 w]], needKeys = false},
  ['spirit']         = {area = [[The Spirit Woods]], dstRoom = [[Entrance to The Spirit Woods]], dirs = [[#8 e;#4 n]], needKeys = false},
  ['allemonde']      = {area = [[Allemonde]], dstRoom = [[The Crypt]], dirs = [[#3 w;#7 n;unlock door;open door;w;n;#3 e;s;unlock door;open door;s;#2 e;#4 s;#3 w;d;w]], needKeys = true},
  ['shire']          = {area = [[The Shire]], dstRoom = [[A Dimly Lit Path]], dirs = [[#8 w;n]], needKeys = false},
  ['garden']         = {area = [[The Garden]], dstRoom = [[Cobble Stone Path]], dirs = [[#6 w;n]], needKeys = false},
  ['dtower']         = {area = [[The Death Tower]], dstRoom = [[The Entrance of the Death Tower]], dirs = [[#6 e;s]], needKeys = false},
  ['lands']          = {area = [[The Lands]], dstRoom = [[Underground River]], dirs = [[#6 e;#2 s;d;w;#10 s]], needKeys = false},
  ['galaxy']         = {area = [[The Galaxy]], dstRoom = [[Inside a Tavern]], dirs = [[#3 n;#7 u;n]], needKeys = false},
  ['zhalur']         = {area = [[Zhalur the Golden]], dstRoom = [[The Docks Along the River]], dirs = [[s;#2 e;#2 s;#2 e;#5 s]], needKeys = false},
  ['roses']          = {area = [[The Warring Roses]], dstRoom = [[A Sheltered Enclave]], dirs = [[#14 w;s;#10 w;#3 s;#4 w;s;u]], needKeys = false},
  ['graveyard']      = {area = [[The New Graveyard]], dstRoom = [[A Path to the Graveyard]], dirs = [[#7 e;#4 n;w]], needKeys = false},
  ['zoo']            = {area = [[The Zoo]], dstRoom = [[Midgaard's Zoo Entrance]], dirs = [[s;#3 w;#5 s]], needKeys = false},
  ['chatdead']       = {area = [[The Chateau of the Dead]], dstRoom = [[A Dark Passage]], dirs = [[#5 w;#4 n;#4 w;open door;#2 w;#2 s;open bookshelf;w;s]], needKeys = false},
  ['itower']         = {area = [[The Ivory Tower]], dstRoom = [[Entrance to the Ivory Tower]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#6 s;w;#5 s;#3 e;#2 s;#2 e]], needKeys = false},
  ['newt']           = {area = [[The Newt Caves]], dstRoom = [[Obsidian Hills]], dirs = [[#7 e;#2 s;e]], needKeys = false},
  ['stower']         = {area = [[The River and Tower of Sorcery]], dstRoom = [[Under the Bridge]], dirs = [[s;#2 e;#2 s;#3 w]], needKeys = false},
  ['graveyardp']     = {area = [[The Graveyard Plus]], dstRoom = [[A Gravel Road on the Graveyard]], dirs = [[s;#3 w;#4 s;#2 e;open grate;s]], needKeys = false},
  ['chatnango']      = {area = [[Le Chateau d'Angoisse]], dstRoom = [[Pathway to the Chateau]], dirs = [[s;#2 e;#2 s;#2 e;#4 s;#4 w;n;#5 w;d;n]], needKeys = false},
  ['pixies']         = {area = [[The Pixies' Garden]], dstRoom = [[At a Winding Iron Gate]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#6 s;w;#8 s]], needKeys = false},
  ['durgathel']      = {area = [[Mt. Durgathel]], dstRoom = [[The Hills]], dirs = [[#7 e;#3 n]], needKeys = false},
  ['goblin']         = {area = [[The Goblin Kingdom]], dstRoom = [[A Path to a Dark Cave]], dirs = [[#14 w;n]], needKeys = false},
  ['palace']         = {area = [[The Evil Palace]], dstRoom = [[Guard of Spirit]], dirs = [[#7 e;#4 n;#3 w;#2 n;#5 w;#2 d;s]], needKeys = false},
  ['myree']          = {area = [[The Myree Orchard]], dstRoom = [[A Clearing]], dirs = [[#8 e;#3 s;#7 e;s]], needKeys = false},
  ['halfling']       = {area = [[The Halfing Village]], dstRoom = [[Entrance to the Halfling Village]], dirs = [[#10 e]], needKeys = false},
  ['lostcity']       = {area = [[The Lost City]], dstRoom = [[The Pool]], dirs = [[s;#2 e;#2 s;#3 e]], needKeys = false},
  ['drowcity']       = {area = [[Drow City]], dstRoom = [[City Entrance]], dirs = [[s;#2 e;#2 s;#3 w;d]], needKeys = false},
  ['thalos']         = {area = [[The City of Thalos]], dstRoom = [[The Grand Gate of Thalos]], dirs = [[s;#2 e;#2 s;#2 e;#4 s;w]], needKeys = false},
  ['dvillage']       = {area = [[The Deserted Village]], dstRoom = [[On a Short Path to a Deserted Village]], dirs = [[#7 w;s]], needKeys = false},
  ['wasteland']      = {area = [[The Wasteland]], dstRoom = [[The Landing]], dirs = [[#6 e;#2 s;d;w;#11 s;#2 e;n]], needKeys = false},
  ['pyramid']        = {area = [[The Great Pyramid]], dstRoom = [[The Rope to the Pyramid]], dirs = [[s;#2 e;#2 s;#2 e;#9 s;e;#4 s;w;#4 s;e;s;#2 e;u]], needKeys = false},
  ['ozymar']         = {area = [[Ozymar's City]], dstRoom = [[The Real Entrance to Ozymar's City]], dirs = [[#14 w;s;#2 w;#2 s;w;s;#3 w;n;#2 w]], needKeys = false},
  ['arachnid']       = {area = [[The Arachnid Archives]], dstRoom = [[An Open Plain]], dirs = [[#14 w;s;#3 w;u;#2 w;n]], needKeys = false},
  ['dwarven']        = {area = [[The Dwarven Kingdom]], dstRoom = [[Path to Dwarven Village]], dirs = [[#7 e;d]], needKeys = false},
  ['gurundi']        = {area = [[Gurundi Forest]], dstRoom = [[The Forest Path]], dirs = [[#5 n;#2 w;#6 n]], needKeys = false},
  ['threggi']        = {area = [[The Threggi Pit]], dstRoom = [[The Oracle of the Everliving]], dirs = [[#5 n;#2 w;#12 n;#2 e;#2 n;#26 u;#6 n]], needKeys = false},
  ['aliens']         = {area = [[The Alien's Den]], dstRoom = [[Outside the Black Hole]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#6 s;w;#7 s;#3 w;s;#3 e]], needKeys = false},
  ['quifaels']       = {area = [[Quifael's Shop]], dstRoom = [[Quifael's Monster Pen]], dirs = [[s;#3 w;#4 s;#2 e;n;unlock door;open door;#2 e;d]], needKeys = true},
  ['outpost']        = {area = [[The Evil Outpost]], dstRoom = [[A Dark Narrow Trail]], dirs = [[#7 w;#2 s;#2 e;s;e;s;e;#2 s;e;n]], needKeys = false},
  ['asylum']         = {area = [[The Midgaard Asylum]], dstRoom = [[Gate to the Asylum]], dirs = [[s;#3 w;#4 s;#2 e;#6 n]], needKeys = false},
  ['vadir']          = {area = [[Vadir Temple]], dstRoom = [[High Priest's Chamber]], dirs = [[s;#3 w;#3 s;#4 e;d;#5 w;n;#2 w;n;e;#2 n;#3 e;open door;#4 s;open gate;s;open curtain;s]], needKeys = false},
  ['bfield']         = {area = [[The Battlefield]], dstRoom = [[The Entrance to the Battlefield]], dirs = [[#7 e;#2 s;e;#2 n]], needKeys = false},
  ['bfieldvillage']  = {area = [[The Battlefield Village]], dstRoom = [[The Dark Gates]], dirs = [[#7 e;#2 s;e;#7 n;#8 e;#2 u;#2 e;#2 d;#4 e;#6 s]], needKeys = false},
  ['pirage']         = {area = [[The Pirate Ship]], dstRoom = [[The Main Deck of Pirate Sloop]], dirs = [[s;#3 e;s;#6 e;#4 s]], needKeys = false},
  ['lostgods']       = {area = [[The Hall of the Lost Gods]], dstRoom = [[Tunnel near the Tavern of the Universe]], dirs = [[#3 n;#7 u;n;e]], needKeys = false},
  ['redferne']       = {area = [[Redferne's Residence]], dstRoom = [[Outside Redferne's Residence]], dirs = [[s;#3 w;#3 s;e;#4 s;e;#5 u]], needKeys = false},
  ['ceiarda']        = {area = [[Cei'Arda]], dstRoom = [[The Entrance to Cei'Arda]], dirs = [[#14 w;s;#4 w]], needKeys = false},
  ['ocean']          = {area = [[The Ocean]], dstRoom = [[Entrance to the Ocean]], dirs = [[s;#3 e;s;#4 e]], needKeys = false},
  ['seaoflove']      = {area = [[The Sea of Love]], dstRoom = [[Wharf]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d]], needKeys = false},
  ['beach']          = {area = [[The Beach]], dstRoom = [[Seashore]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#6 s;w;#4 s]], needKeys = false},
  ['festival']       = {area = [[The Festival of Antiquity]], dstRoom = [[Below a Small Platform]], dirs = [[#14 w;s;#10 w;#3 s;#4 w;s]], needKeys = false},
  ['desert']         = {area = [[The Desert and Lake]], dstRoom = [[Desert]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#6 s;w;#5 s;#4 w]], needKeys = false},
  ['grail']          = {area = [[The Quest for the Holy Grail]], dstRoom = [[The Entrance to The Quest for the Holy Grail.]], dirs = [[#14 w;s;#10 w;#4 n;#8 w;#3 s;w]], needKeys = false},
  ['vamps']          = {area = [[Le Theatre des Vampyres]], dstRoom = [[Outside The Theatre Des Vampyres]], dirs = [[s;#3 w;#4 s;#2 e;#3 n;e;n]], needKeys = false},
  ['kings']          = {area = [[The King's Castle]], dstRoom = [[The King's Road]], dirs = [[#18 e]], needKeys = false},
  ['cloudcity']      = {area = [[Cloud City]], dstRoom = [[A Fluffy White Cloud]], dirs = [[#3 n;#4 u;n]], needKeys = false},
  ['loftwick']       = {area = [[Loftwick]], dstRoom = [[Entrance to the Lost City of Loftwick]], dirs = [[s;#2 e;#2 s;#2 e;#9 s;e;#4 s;w;#4 s;e;#5 s;n;#2 s;e;n;e;n;e;d]], needKeys = false},
  ['elemental']      = {area = [[The Elemental Canyon]], dstRoom = [[A Mountain Path]], dirs = [[#7 e;#2 s;e;n]], needKeys = false},
  ['wolvescave']     = {area = [[The Wolves Cave]], dstRoom = [[The River]], dirs = [[s;#2 e;#2 s;#3 w;#6 s;e]], needKeys = false},
  ['morgoth']        = {area = [[Morgoth]], dstRoom = [[Between Two Hills]], dirs = [[#7 e;#3 n;e]], needKeys = false},
  ['cathedral']      = {area = [[The Dark Cathedral]], dstRoom = [[Rutted Path]], dirs = [[#6 e;n]], needKeys = false},
  ['monk']           = {area = [[The Monk Monastary]], dstRoom = [[Path through The Forest]], dirs = [[#11 w;n]], needKeys = false},
  ['quickland']      = {area = [[QuickLand]], dstRoom = [[The Sinister Forest Path]], dirs = [[#8 w;#2 s;e;s;#2 e]], needKeys = false},
  ['greatdesert']    = {area = [[The Great Desert]], dstRoom = [[Great Desert]], dirs = [[s;#2 e;#2 s;#2 e;#9 s;e;#4 s;w;#4 s;e]], needKeys = false},
  ['blackpoolswamp'] = {area = [[Blackpool Swamp]], dstRoom = [[The Marshes of Blackpool]], dirs = [[s;#2 e;#2 s;#3 w;#2 s;w]], needKeys = false},
  ['golemkingdom']   = {area = [[The Golem Kingdom]], dstRoom = [[A Dark Passage]], dirs = [[s;#2 e;#2 s;#3 w;#2 s;#2 w;n;#2 w;s;#3 w;s;#2 w]], needKeys = false},
  ['chaoslands']     = {area = [[Chaos Lands]], dstRoom = [[Deep in a Dark and Deadly Swamp]], dirs = [[s;#2 e;#2 s;#3 w;#2 s;#2 w;s;#2 e;#5 s;#3 w]], needKeys = false},
  ['zyca']           = {area = [[Zyca City]], dstRoom = [[A Beautiful Path]], dirs = [[#14 w;#5 n]], needKeys = false},
  ['underworld']     = {area = [[The UnderWorld]], dstRoom = [[Blind Alley]], dirs = [[s;#3 w;#3 s;#4 e;d;#3 w;#2 s;#2 e;s;e;#2 s;w;d;#2 n;e;n;e]], needKeys = false},
  ['romnia']         = {area = [[The Village of Romnia]], dstRoom = [[The Road]], dirs = [[#7 e;#3 s]], needKeys = false},
  ['despair']        = {area = [[The Castle of Despair]], dstRoom = [[The Stezja Road]], dirs = [[#7 e;#3 s;#2 e;#7 w;s;#4 w]], needKeys = false},
  ['lorien']         = {area = [[Lorien]], dstRoom = [[The Oak Forest]], dirs = [[#7 e;#5 n;e]], needKeys = false},
  ['messia']         = {area = [[Straits of Messia]], dstRoom = [[Entering the Straits of Messia]], dirs = [[s;#2 e;#2 s;#3 w;#2 s;#2 w;n;#2 w;s;#3 w;s;#4 w;#2 s;#5 w;#3 n;#2 w;#2 n;w;#2 n;#2 d;#2 n;#2 e;#3 n;w]], needKeys = false},
  ['swamp']          = {area = [[The Swamp]], dstRoom = [[On the Edge of the Huge Dreadful Swamp]], dirs = [[#10 w;n]], needKeys = false},
  ['swampcaves']     = {area = [[The Swamp and Secret Caves]], dstRoom = [[Large Tunnel]], dirs = [[#10 w;n;w;#2 n;w;n;w;n;#2 e;#2 n;w;#2 n;#2 e;s;e;s;e;open secret;d;#3 e;n;#2 d]], needKeys = false},
  ['souls']          = {area = [[The Prison of Souls]], dstRoom = [[A Path Through Barren Woods]], dirs = [[#8 e;#3 n;#7 e;#3 n;w;#5 n;e;n]], needKeys = false},
  ['rocs']           = {area = [[The Roc Aviary]], dstRoom = [[The Tree Trunk]], dirs = [[#7 e;#2 s;e;#2 s;e;n]], needKeys = false},
  ['mercador']       = {area = [[The Templars Mercador]], dstRoom = [[Great Desert]], dirs = [[s;#2 e;#2 s;#2 e;#9 s;e;#4 s;w;#4 s;e;#5 s;n;s;e;#2 n;#3 e;w;e]], needKeys = false},
  ['janus']          = {area = [[Rainforest of Janus]], dstRoom = [[A Tepid River]], dirs = [[s;#2 e;#2 s;#2 e;#9 s;e;#4 s;w;#4 s;e;#5 s;n;s;e;#2 n;#3 e;w;#2 e;n;e;#3 s;w;n;w;#2 s;#4 e;s;w;n;#2 e;d;#2 n;open door;d;#2 e;open door;d;open door;#3 s;e;d;e]], needKeys = false},
  ['gnolls']         = {area = [[The Gnoll Fortress]], dstRoom = [[Entrance to a Dark Cave]], dirs = [[#7 w;#2 s;#2 e;s;e;s;e;#2 s;e;#5 n;open gate;#3 n;d;#4 n;#2 d;s]], needKeys = false},
  ['sagrethi']       = {area = [[The Cave of the Sag'rethi]], dstRoom = [[A Path in a Darkened Cave]], dirs = [[#7 w;#2 s;#2 e;s;e;s;e;#2 s;e;#5 n;open gate;#3 n;d;#4 n;#2 d;#3 s;w;n;w;#3 s;d]], needKeys = false},
  ['safari']         = {area = [[The Safari]], dstRoom = [[A Grassy Trail]], dirs = [[#5 n;#2 w;#4 n;#5 e;n]], needKeys = false},
  ['jungle']         = {area = [[Slaadi Jungle]], dstRoom = [[Near the Jungle]], dirs = [[#7 e;#2 s;e;#2 s;e;#3 s;#2 e]], needKeys = false},
  ['dkingdom1']      = {area = [[Dark Kingdom I]], dstRoom = [[A Dry Riverbed]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#4 s;#4 w;#2 s;d;w;s;w]], needKeys = false},
  ['dkingdom2']      = {area = [[Dark Kingdom II]], dstRoom = [[A Ruined Tower]], dirs = [[#14 w;s;#7 w;s;#2 w;s;d;#4 s;#4 w;#2 s;d;#2 e;n;w;n;w;n;e;n;#4 e;#2 n;w]], needKeys = false},
  ['fvalley']        = {area = [[Forgotten Valley]], dstRoom = [[A Narrow Gulley]], dirs = [[#7 e;#2 s;e;#10 n;e;n;#3 e;n;#2 e]], needKeys = false},
  ['lunar']          = {area = [[The Dwarven Lunar Mines I]], dstRoom = [[A Small, Clandestine Chamber]], dirs = [[#7 e;d;#3 n;e;unlock door;open door;e;#2 d;n]], needKeys = true}
}
